/**********************************************************************************************************************
 * \file ap.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "ap.h"
#include "LKAS.h"
#include "ACC.h"
<<<<<<< Updated upstream
=======
#include "GPIO_LED_Button.h"
#include "MULTICAN.h"
#include "ASCLIN_UART.h"
>>>>>>> Stashed changes

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
<<<<<<< Updated upstream


=======
uint8 left_flag = 0;
uint8 right_flag = 0;
int8_t yaw_rate = 0;
>>>>>>> Stashed changes
adas_controller_t adas_controller;
float ultra_dis1;
float ultra_dis2;
float ultra_dis3;
<<<<<<< Updated upstream


uint8 left_flag = 0;
uint8 right_flag = 0;
int8_t yaw_rate = 0;

=======
>>>>>>> Stashed changes
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void app_task_100ms(void);
void app_task_50ms(void);
void app_scheduling(void);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
uint8 CANTxMessage[8] = {0,};

void ap_init(void)
{

}

void ap_main(void)
{
//  uint32_t new_target_freq[MOTOR_MAX_CH] = {500, 500, 500, 500};
//  motor_update_target(new_target_freq, 1);
//  motor_start();
  scheduler_init();
  ACC_initialize();
  LKAS_initialize();

  while(1)
  {
<<<<<<< Updated upstream

      uint32 tick = 5000;
      led_toggle(_DEF_LED1);
      set_car_distance(ULTRA_LEFT);
      set_car_distance(ULTRA_CENTER);
      set_car_distance(ULTRA_RIGHT);
      ultra_dis1 = get_car_distance(ULTRA_LEFT);    // 좌측
      ultra_dis2 = get_car_distance(ULTRA_CENTER);  // 중앙
      ultra_dis3 = get_car_distance(ULTRA_RIGHT);   // 우측
      while(tick--);

      app_scheduling();

    control_LED();
=======
      app_scheduling();

      control_LED();
//      uint32 tick = 5000;
//        set_car_distance(ULTRA_LEFT);
//        set_car_distance(ULTRA_CENTER);
//        set_car_distance(ULTRA_RIGHT);
//        ultra_dis1 = get_car_distance(ULTRA_LEFT);    // 좌측
//        ultra_dis2 = get_car_distance(ULTRA_CENTER);  // 중앙
//        ultra_dis3 = get_car_distance(ULTRA_RIGHT);   // 우측
//        while(tick--);
>>>>>>> Stashed changes
//      uint32 tick = 5000;
//      led_toggle(_DEF_LED1);
//      while(tick--);
//      receive_uart_message();
//      transmitCanMessage(CANTxMessage);
//      uint32 tick = 5000;
//      while(tick--);


      //버튼이 눌렸는지
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
  }
}

void app_scheduling(void)
{
<<<<<<< Updated upstream
    if (st_scheduling_info.u8nu_scheduling_100ms_flag == 1u)
    {
        st_scheduling_info.u8nu_scheduling_100ms_flag = 0u;
        app_task_100ms();
    }
=======
>>>>>>> Stashed changes
    if (st_scheduling_info.u8nu_scheduling_50ms_flag == 1u)
    {
        st_scheduling_info.u8nu_scheduling_50ms_flag = 0u;
        app_task_50ms();
    }
<<<<<<< Updated upstream
=======
    if (st_scheduling_info.u8nu_scheduling_100ms_flag == 1u)
    {
        st_scheduling_info.u8nu_scheduling_100ms_flag = 0u;
        app_task_100ms();
    }

>>>>>>> Stashed changes
}

void app_task_50ms(void)
{

    receive_uart_message();//uart 버퍼 확인
<<<<<<< Updated upstream
    if(l_cur==1&&r_cur==1){//깜빡이가 안켜졌을때
        CANTxMessage[0] = 0;
        //g_rxData[0] = -2;//test data
        rtU1.heading_error = g_rxData[0];
        rtU1.heading_error /=10;
        rtU.distance=read_distance(0);//초음파센서 값 확인
        if(Rx_arr[0]>=0 && Rx_arr[0]<=3){
            rtU.current_speed = Rx_arr[0];
        }
        else{
            rtU.current_speed = 0;
        }

        ACC_step();//acc_step()
        CANTxMessage[1] = rtY.control_speed*10;
        LKAS_step();//lkas_step()
        CANTxMessage[2] = rtY1.yaw_rate;
    }
    else if(l_cur==0){//좌깜빡이가 켜졌을때 10번 신호를 주고 끔
        if(read_distance(1)>200){
            CANTxMessage[0] = 1;
            left_flag++;
            if(left_flag>10){
                left_flag = 0;
                l_cur ==0;
            }
        }


    }
    else if(r_cur==0){//우깜빡이가 켜졌을때 10번 신호를 주고 끔
        if(read_distance(2)>200){
            CANTxMessage[0] = 2;
            right_flag++;
            if(right_flag>10){
                right_flag = 0;
                r_cur ==0;
            }
        }
=======

    if(l_cur==0&&r_cur==0){//깜빡이가 안켜졌을때

        CANTxMessage[0] = 0;
        //g_rxData[0] = -2;//test data
        rtU1.heading_error = g_rxData[0];
        rtU1.heading_error /=1000;
        set_car_distance(ULTRA_CENTER);
        ultra_dis2 = get_car_distance(ULTRA_CENTER);
        rtU.distance=ultra_dis2;//초음파센서 값 확인
//        if(Rx_arr[0]>=0 && Rx_arr[0]<=2){
            rtU.current_speed = ((float) Rx_arr[0]/ 255.0f) * 2.0f;
//        }
//        else{
//            rtU.current_speed = 0;
//        }

        ACC_step();//acc_step()
        CANTxMessage[1] = (uint8_t)((rtY.control_speed / 2.0f) * 255.0f + 0.5f);
        LKAS_step();//lkas_step()
        CANTxMessage[2] = (uint8_t)(((rtY1.yaw_rate + 0.5f) / 1.0f) * 255.0f + 0.5f);
    }
    else if(l_cur==1){//좌깜빡이가 켜졌을때 10번 신호를 주고 끔
        set_car_distance(ULTRA_CENTER);
        ultra_dis1 = get_car_distance(ULTRA_CENTER);
        if(ultra_dis1<15){
            CANTxMessage[0] = 1;
            left_flag++;
            if(left_flag>50){
                left_flag = 0;
                l_cur =0;
            }
        }
        else {
            CANTxMessage[0] = 0;
            rtU1.heading_error = g_rxData[0];
            rtU1.heading_error /=1000;
            set_car_distance(ULTRA_CENTER);
            ultra_dis2 = get_car_distance(ULTRA_CENTER);
            rtU.distance=ultra_dis2;//초음파센서 값 확인
//            if(Rx_arr[0]>=0 && Rx_arr[0]<=3){
                rtU.current_speed = ((float) Rx_arr[0]/ 255.0f) * 2.0f;
//            }
//            else{
//                rtU.current_speed = 0;
//            }

            ACC_step();//acc_step()
            CANTxMessage[1] = (uint8_t)((rtY.control_speed / 2.0f) * 255.0f + 0.5f);
            LKAS_step();//lkas_step()
            CANTxMessage[2] = (uint8_t)(((rtY1.yaw_rate + 0.5f) / 1.0f) * 255.0f + 0.5f);
        }


    }
    else if(r_cur==1){//우깜빡이가 켜졌을때 10번 신호를 주고 끔
        set_car_distance(ULTRA_RIGHT);
        ultra_dis3 = get_car_distance(ULTRA_RIGHT);
        if(ultra_dis3<15){
            CANTxMessage[0] = 2;
            right_flag++;
            if(right_flag>50){
                right_flag = 0;
                r_cur =0;
            }
        }
        else {
            CANTxMessage[0] = 0;
            rtU1.heading_error = g_rxData[0];
            rtU1.heading_error /=1000;
            set_car_distance(ULTRA_CENTER);
            ultra_dis2 = get_car_distance(ULTRA_CENTER);
            rtU.distance=ultra_dis2;//초음파센서 값 확인
//            if(Rx_arr[0]>=0 && Rx_arr[0]<=3){
            rtU.current_speed = ((float) Rx_arr[0]/ 255.0f) * 2.0f;
//            }
//            else{
//                rtU.current_speed = 0;
//            }

            ACC_step();//acc_step()
            CANTxMessage[1] = (uint8_t)((rtY.control_speed / 2.0f) * 255.0f + 0.5f);
            LKAS_step();//lkas_step()
            CANTxMessage[2] = (uint8_t)(((rtY1.yaw_rate + 0.5f) / 1.0f) * 255.0f + 0.5f);
        }
>>>>>>> Stashed changes
    }

    //버튼 플래그 올라가있으면 button값 변
}


void app_task_100ms(void)
{
    transmitCanMessage(CANTxMessage);//CAN send(button,control_speed,yaw_rate)
}

