/**********************************************************************************************************************
 * \file bsp.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent g_cpuSyncEvent = 0;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*------------------------------------------------------------------------------------------------*/
/* bspInit: Watchdog 비활성화, 포트·STM 초기화                                                   */
/*------------------------------------------------------------------------------------------------*/
void bsp_init(void)
{
    IfxCpu_enableInterrupts();

    /* 1) Watchdog 비활성화 */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

}

//
///*------------------------------------------------------------------------------------------------*/
///* delay_ms: STM 폴링을 이용한 밀리초 딜레이                                                      */
///*------------------------------------------------------------------------------------------------*/
//void delay_ms(uint32 ms)
//{
//    uint32 ticks = (uint32)((uint64)BSP_STM_FREQ * ms / 1000);
//    uint32 target = IfxStm_getContext(BSP_STM_CHANNEL)->TIM0 + ticks;
//
//    /* 오버플로우 안전 처리 */
//    if (target < IfxStm_getContext(BSP_STM_CHANNEL)->TIM0) {
//        /* 카운터가 롤오버될 때까지 대기 */
//        while (IfxStm_getContext(BSP_STM_CHANNEL)->TIM0 >= startTick) { }
//    }
//    /* 남은 만큼 대기 */
//    while (IfxStm_getContext(BSP_STM_CHANNEL)->TIM0 < target) { }
//}
//
///*------------------------------------------------------------------------------------------------*/
///* delay_us: STM 폴링을 이용한 마이크로초 딜레이                                                  */
///*------------------------------------------------------------------------------------------------*/
//void delay_us(uint32 us)
//{
//    uint32 ticks = (uint32)((uint64)BSP_STM_FREQ * us / 1_000_000);
//    uint32 start = IfxStm_getContext(BSP_STM_CHANNEL)->TIM0;
//    uint32 current;
//
//    do {
//        current = IfxStm_getContext(BSP_STM_CHANNEL)->TIM0;
//    } while ((current - start) < ticks);
//}
//
///*------------------------------------------------------------------------------------------------*/
///* bspGetMillis: 시스템 시작 이후 경과된 시간(밀리초) 반환                                        */
///*------------------------------------------------------------------------------------------------*/
//uint32 bspGetMillis(void)
//{
//    uint32 now = IfxStm_getContext(BSP_STM_CHANNEL)->TIM0;
//    uint32 elapsedTicks;
//
//    if (now >= startTick) {
//        elapsedTicks = now - startTick;
//    } else {
//        /* 타이머 롤오버 처리 */
//        elapsedTicks = (0xFFFFFFFF - startTick) + now;
//    }
//
//    return (uint32)((uint64)elapsedTicks * 1000 / BSP_STM_FREQ);
//}
//
///*------------------------------------------------------------------------------------------------*/
///* bspErrorHandler: 오류 발생 시 호출                                                          */
///*------------------------------------------------------------------------------------------------*/
//void bspErrorHandler(void)
//{
//    /* 모든 인터럽트 비활성화 */
//    IfxCpu_disableInterrupts();
//
//    /* LED0를 깜빡이며 오류 표시(무한 루프) */
//    while (1)
//    {
//        IfxPort_togglePin(IfxPort_Pin_led0);
//        delay_ms(250);
//    }
//}

