/**********************************************************************************************************************
 * \file bsp.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BSP_BSP_H_
#define BSP_BSP_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "def.h"

#include <Ifx_Cfg.h>                   /* Do not remove this include */
#include <IfxCpu_Intrinsics.h> /* Do not remove this include */
#include <Ifx_Assert.h>     /* Do not remove this include */

#include <IfxCpu.h>        // 인터럽트, CPU 제어
#include <IfxPort.h>       // 포트 제어 (LED 등)

#include <IfxSrc.h>
#include <IfxStm.h>        // STM(System Timer) 제어
//#include <IfxStm_cfg.h>   // STM 리소스 매핑 (MODULE_STM0 등)

#include <IfxScuWdt.h>     // Watchdog 제어
#include <IfxScuCcu.h>


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define BSP_STM_CHANNEL    IfxStm_ResourceCpu0  /**< 사용할 STM 채널 정의 */
#define BSP_STM_FREQ       (IfxStm_getFrequency(BSP_STM_CHANNEL)) /**< STM 클럭 주파수 */
#define BSP_DEFAULT_TIMER   (&MODULE_STM0)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/**
 * @brief BSP 초기화
 *        - Watchdog 비활성화
 *        - Port 및 STM 초기화
 */
void bsp_init(void);

/**
 * @brief Delay for approximately ms 밀리초
 * @param ms  대기할 시간 (밀리초)
 */
void delay_ms(uint32 ms);

/**
 * @brief Delay for approximately us 마이크로초
 * @param us  대기할 시간 (마이크로초)
 */
void delay_us(uint32 us);

/**
 * @brief 시스템이 시작된 후 경과한 시간을 밀리초 단위로 반환
 * @return ms 단위 경과 시간
 */
uint32 bspGetMillis(void);

/**
 * @brief 에러 발생 시 호출할 핸들러
 */
void bspErrorHandler(void);

#endif /* BSP_BSP_H_ */
