/**********************************************************************************************************************
 * \file led.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "led.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

led_tbl_t led_tbl[LED_MAX_CH] =
        {
            {&MODULE_P10, 2, IfxPort_State_high, IfxPort_State_low}
        };

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* 초기화 */
bool led_init(void)
{
    bool ret = true;

    for (uint8_t i = 0; i < LED_MAX_CH; i++)
    {
        IfxPort_setPinModeOutput(
          led_tbl[i].port,
          led_tbl[i].pin,
          IfxPort_OutputMode_pushPull,          // Push-pull 출력
          IfxPort_OutputIdx_general
        );
        led_off(i);
    }

    return ret;
}

void led_on(uint8_t ch)
{
    if (ch >= LED_MAX_CH) return;
    // STM 예제는 low-level active: SET→OFF, RESET→ON
    IfxPort_setPinHigh(led_tbl[ch].port, led_tbl[ch].pin);
}

void led_off(uint8_t ch)
{
    if (ch >= LED_MAX_CH) return;
    IfxPort_setPinLow(led_tbl[ch].port, led_tbl[ch].pin);
}

void led_toggle(uint8_t ch)
{
    if (ch >= LED_MAX_CH) return;
    IfxPort_togglePin(led_tbl[ch].port, led_tbl[ch].pin);
}

