/**********************************************************************************************************************
 * \file motor.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "motor.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define CLK_FREQ   1000000.0f  // CMU_CLK0: 1MHz
#define PWM_FREQ   500
#define PULSE_US   300
#define TABLE_LEN  101

#define ISR_PRIORITY_ATOM0  10
#define ISR_PRIORITY_ATOM1  11
#define ISR_PRIORITY_ATOM2  12
#define ISR_PRIORITY_ATOM3  13

IFX_INTERRUPT(atom0_isr, 0, ISR_PRIORITY_ATOM0);
IFX_INTERRUPT(atom2_isr, 0, ISR_PRIORITY_ATOM1);
IFX_INTERRUPT(atom4_isr, 0, ISR_PRIORITY_ATOM2);
IFX_INTERRUPT(atom6_isr, 0, ISR_PRIORITY_ATOM3);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Timer atomTimers[MOTOR_MAX_CH];

IfxGtm_Atom_ToutMap* atomPins[MOTOR_MAX_CH] = {
    &IfxGtm_ATOM0_0_TOUT0_P02_0_OUT,
    &IfxGtm_ATOM0_2_TOUT2_P02_2_OUT,
    &IfxGtm_ATOM0_4_TOUT4_P02_4_OUT,
    &IfxGtm_ATOM0_6_TOUT6_P02_6_OUT

};

typedef enum {
    MOTOR_STATE_STOP,
    MOTOR_STATE_ACCEL,
    MOTOR_STATE_CONST,
    MOTOR_STATE_DECEL
} MotorState;

MotorState motor_state[MOTOR_MAX_CH] = {0};
//uint32_t accel_table[TABLE_LEN] = {0};
const uint16_t accel_table[TABLE_LEN] = {
    0, 5, 10, 15, 20, 25, 30, 35, 40, 45,
    50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
    100, 105, 110, 115, 120, 125, 130, 135, 140, 145,
    150, 155, 160, 165, 170, 175, 180, 185, 190, 195,
    200, 205, 210, 215, 220, 225, 230, 235, 240, 245,
    250, 255, 260, 265, 270, 275, 280, 285, 290, 295,
    300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
    350, 355, 360, 365, 370, 375, 380, 385, 390, 395,
    400, 405, 410, 415, 420, 425, 430, 435, 440, 445,
    450, 455, 460, 465, 470, 475, 480, 485, 490, 495,
    500
};
uint8_t accel_index[MOTOR_MAX_CH] = {0};
uint32_t target_freq[MOTOR_MAX_CH] = {0};

uint8_t accel = 1;


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* 초기화 */
void motor_init(){
    gtm_clock_init();
    motor_timer_init();

}

void gtm_clock_init() {
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);
}

void motor_timer_init() {
    for (int i = 0; i < MOTOR_MAX_CH; ++i) {
        IfxGtm_Atom_Timer_Config config;
        IfxGtm_Atom_Timer_initConfig(&config, &MODULE_GTM);

        config.atom = atomPins[i]->atom;
        config.timerChannel = atomPins[i]->channel;
        config.clock = IfxGtm_Cmu_Clk_0;
        config.base.frequency = 0;
        config.base.trigger.enabled = TRUE;
        config.base.trigger.outputEnabled = TRUE;
        config.base.trigger.outputMode = IfxPort_OutputMode_pushPull;
        config.base.trigger.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;
        config.base.trigger.risingEdgeAtPeriod = TRUE;
        config.base.trigger.triggerPoint = (uint32)(PULSE_US / 1e6f * CLK_FREQ);
        config.base.countDir = IfxStdIf_Timer_CountDir_up;
        config.initPins = TRUE;
        config.triggerOut = atomPins[i];
        config.base.isrPriority = i + 10;
        config.base.isrProvider = IfxSrc_Tos_cpu0;


        // Initialize timer
        IfxGtm_Atom_Timer_init(&atomTimers[i], &config);
        IfxGtm_Atom_Timer_setSingleMode(&atomTimers[i], FALSE);

        // Enable output and channel manually (recommended)
        uint16 mask = 1 << config.timerChannel;
        IfxGtm_Atom_Agc_enableChannels(atomTimers[i].agc, mask, 0, TRUE);
        IfxGtm_Atom_Agc_enableChannelsOutput(atomTimers[i].agc, mask, 0, TRUE);

        // Set Compare1 (trigger point) again to ensure PWM works
        IfxGtm_Atom_Timer_setTrigger(&atomTimers[i], config.base.trigger.triggerPoint);

        // Interrupt (Compare0)
        IfxGtm_Atom_Ch_setNotification(atomTimers[i].atom, config.timerChannel, IfxGtm_IrqMode_level, TRUE, FALSE);
        volatile Ifx_SRC_SRCR* src = IfxGtm_Atom_Ch_getSrcPointer(&MODULE_GTM, config.atom, config.timerChannel);
        IfxSrc_init(src, config.base.isrProvider, config.base.isrPriority);
        IfxSrc_enable(src);
    }

    // Apply update and run
    for (int i = 0; i < MOTOR_MAX_CH; ++i)
        IfxGtm_Atom_Timer_addToChannelMask(&atomTimers[0], atomPins[i]->channel);

}

void motor_start()
{
    IfxGtm_Atom_Timer_run(&atomTimers[0]);
    IfxGtm_Atom_Timer_applyUpdate(&atomTimers[0]);
    motor_set_all_speed(1);
}

void motor_set_all_speed(uint32_t freq_hz)
{
    uint16 channelMask = 0;

    for (int i = 0; i < MOTOR_MAX_CH; ++i)
    {

        if (freq_hz == 0)
            continue;

        Ifx_TimerValue period = (Ifx_TimerValue)(CLK_FREQ / freq_hz);
        Ifx_TimerValue trigger = (Ifx_TimerValue)((PULSE_US * CLK_FREQ) / 1000000);

        // 유효성 보장
        if (trigger >= period) trigger = period - 1;

        // 채널별 설정
        IfxGtm_Atom_Timer_disableUpdate(&atomTimers[i]);

        IfxGtm_Atom_Timer_setPeriod(&atomTimers[i], period);           // sets Compare1
        IfxGtm_Atom_Timer_setTrigger(&atomTimers[i], trigger);         // sets Compare1 (output)


        // 마스크에 현재 채널 추가
        channelMask |= (1 << atomPins[i]->channel);
    }

    // 동기 업데이트: 모든 채널 force update 후 trigger
    Ifx_GTM_ATOM_AGC* agc = atomTimers[0].agc;
    IfxGtm_Atom_Agc_setChannelsForceUpdate(agc, channelMask, 0, 0, 0);
    IfxGtm_Atom_Agc_trigger(agc);  // 모든 채널 동시에 업데이트
}

void motor_update_speed(uint8_t id, uint32_t freq_hz)
{
    if (freq_hz == 0) return;

    Ifx_TimerValue period = CLK_FREQ / freq_hz;
    Ifx_TimerValue trigger = (PULSE_US * CLK_FREQ) / 1000000;

    if (trigger >= period)
        trigger = period - 1;

    IfxGtm_Atom_Timer_disableUpdate(&atomTimers[id]);

IfxGtm_Atom_Timer_setPeriod(&atomTimers[id], period);
    IfxGtm_Atom_Timer_setTrigger(&atomTimers[id], trigger);

    uint16 mask = 1 << atomPins[id]->channel;
    IfxGtm_Atom_Agc_setChannelsForceUpdate(atomTimers[id].agc, mask, 0, 0, 0);
    IfxGtm_Atom_Agc_trigger(atomTimers[id].agc);
}

void motor_update_target(uint32_t new_target_freq[MOTOR_MAX_CH], uint8_t new_accel)
{
    for (int i = 0; i < MOTOR_MAX_CH; ++i)
    {
        target_freq[i] = new_target_freq[i];
        motor_state[i] = (target_freq[i] > accel_table[accel_index[i]])
                         ? MOTOR_STATE_ACCEL
                         : MOTOR_STATE_DECEL;
    }
    accel = new_accel;
}


void handle_motor_isr(uint8_t id)
{
    IfxGtm_Atom_Timer_acknowledgeTimerIrq(&atomTimers[id]);

    switch (motor_state[id])
    {
        case MOTOR_STATE_ACCEL:
            if (accel_table[accel_index[id]] < target_freq[id])
            {
                accel_index[id] += accel;
                if (accel_index[id] >= TABLE_LEN)
                {
                    accel_index[id] = TABLE_LEN - 1;
                    motor_state[id] = MOTOR_STATE_CONST;
                }
            }
            else
            {
                motor_state[id] = MOTOR_STATE_CONST;
            }
            break;

        case MOTOR_STATE_DECEL:
            if (accel_index[id] > accel)
            {
                accel_index[id] -= accel;
            }
            else
            {
                accel_index[id] = 0;
                motor_state[id] = MOTOR_STATE_STOP;
            }
            break;

        default:
            break;
    }

    uint32_t next_freq = accel_table[accel_index[id]];
    motor_update_speed(id, next_freq);
}

void atom0_isr(void) { handle_motor_isr(0); }
void atom2_isr(void) { handle_motor_isr(1); }
void atom4_isr(void) { handle_motor_isr(2); }
void atom6_isr(void) { handle_motor_isr(3); }
