/**********************************************************************************************************************
 * \file ultrasound.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <ultrasonic.h>
#include "IfxPort.h"
#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/


#define ECHO_PORT   &MODULE_P02

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
const int trig_pins[] = {0, 4, 4};
const int echo_pins[] = {1, 3, 5};

boolean flag;
boolean flag2;
float distance_cm;
Ifx_P* TRIG_PORT = &MODULE_P02;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void ultrasonic_init(){
    IfxPort_setPinModeOutput(&MODULE_P02, 0, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P02, 0);
    IfxPort_setPinModeOutput(&MODULE_P10, 4, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P10, 4);
    IfxPort_setPinModeOutput(&MODULE_P02, 4, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P02, 4);

    IfxPort_setPinModeInput(ECHO_PORT, 1, IfxPort_InputMode_pullDown);
    IfxPort_setPinModeInput(ECHO_PORT, 3, IfxPort_InputMode_pullDown);
    IfxPort_setPinModeInput(ECHO_PORT, 5, IfxPort_InputMode_pullDown);
}

float ultrasonic_read_distance(int num){
    unsigned char TRIG_PIN = trig_pins[num];
    unsigned char ECHO_PIN = echo_pins[num];
    if (num == 1){
        TRIG_PORT = &MODULE_P10;
    }
    else{
        TRIG_PORT = &MODULE_P02;
    }
    // 10us Trigger
    IfxPort_setPinHigh(TRIG_PORT, TRIG_PIN);
    waitTime(IfxStm_getTicksFromMicroseconds(BSP_DEFAULT_TIMER, 10));
    IfxPort_setPinLow(TRIG_PORT, TRIG_PIN);

    // Echo 핀 상승엣지 대기
    flag = IfxPort_getPinState(ECHO_PORT, ECHO_PIN);
    while (flag == 0){
        flag = IfxPort_getPinState(ECHO_PORT, ECHO_PIN);
    }

    uint64 start = IfxStm_get(BSP_DEFAULT_TIMER);

    // Echo 핀 하강엣지 대기
    flag = IfxPort_getPinState(ECHO_PORT, ECHO_PIN);
    while (flag == 1){
        flag = IfxPort_getPinState(ECHO_PORT, ECHO_PIN);
    }

    uint64 end = IfxStm_get(BSP_DEFAULT_TIMER);
    uint64 duration_ticks = end - start;

    // 시간(μs)로 변환
    float duration_us = convert_ticks_to_us(BSP_DEFAULT_TIMER, duration_ticks);

    // 거리 계산
    distance_cm = duration_us / 58.0f;

    return distance_cm;
}

float32 convert_ticks_to_us(Ifx_STM *stm, uint64 ticks)
{
    float32 freqHz = (float32)IfxStm_getFrequency(stm);  // 예: 100 MHz
    return (float32)ticks * 1e6f / freqHz;
}
